/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Project/AI8051_north_bridge/al_ip/fifo_1kx9.v
 ** Date	:	2024 11 27
 ** TD version	:	4.6.121343
\************************************************************/

`timescale 1ns / 1ps

module fifo_1kx9 (
	rst,
	di, clkw, we,
	do, clkr, re,
	empty_flag, aempty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [8:0] di;
	input clkw, we;
	input clkr,re;

	output [17:0] do;
	output empty_flag, aempty_flag;
	output full_flag, afull_flag;

EF2_LOGIC_FIFO #(
 	.DATA_WIDTH_W(9),
	.DATA_WIDTH_R(18),
	.DATA_DEPTH_W(1024),
	.DATA_DEPTH_R(512),
	.ENDIAN("BIG"),
	.RESETMODE("ASYNC"),
	.E(0),
	.F(1024),
	.ASYNC_RESET_RELEASE("SYNC"),
	.AE(6),
	.AF(516))
logic_fifo(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clkr),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(aempty_flag),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule