/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/xiaoyu.hong/AI8051_north_bridge/al_ip/internal_m3_core.v
 ** Date	:	2024 11 25
 ** TD version	:	4.6.121343
\************************************************************/

`timescale 1ns / 1ps

module internal_m3_core ( ppm_clk,
	i2s_mst_clk,
	ppm_rstn,
	h2h_haddr,
	h2h_htrans,
	h2h_hwrite,
	h2h_hsize,
	h2h_hburst,
	h2h_hprot,
	h2h_hwdata,
	h2h_hrdata,
	h2h_hreadyout,
	h2h_hresp,
	h2h_mclk,
	h2h_rstn,
	ahbslave_dma_req,
	ahbslave_dma_single,
	ahbslave_dma_ack,
	sleep_out,
	usr_reg,
	qspi_rxd,
	qspi_txd,
	qspi_sclk,
	qspi_ss,
	qspi_oen,
	gpio_h0_out,
	gpio_h0_oe_n,
	gpio_h0_in,
	gpio_h1_out,
	gpio_h1_oe_n,
	gpio_h1_in,
	gpio_h2_out,
	gpio_h2_oe_n,
	gpio_h2_in,
	gpio_h3_out,
	gpio_h3_oe_n,
	gpio_h3_in,
	gpio_h4_out,
	gpio_h4_oe_n,
	gpio_h4_in,
	gpio_h5_out,
	gpio_h5_oe_n,
	gpio_h5_in,
	gpio_h6_out,
	gpio_h6_oe_n,
	gpio_h6_in,
	gpio_h7_out,
	gpio_h7_oe_n,
	gpio_h7_in,
	gpio_h8_out,
	gpio_h8_oe_n,
	gpio_h8_in,
	gpio_h9_out,
	gpio_h9_oe_n,
	gpio_h9_in,
	gpio_h10_out,
	gpio_h10_oe_n,
	gpio_h10_in,
	gpio_h11_out,
	gpio_h11_oe_n,
	gpio_h11_in,
	gpio_h12_out,
	gpio_h12_oe_n,
	gpio_h12_in,
	gpio_h13_out,
	gpio_h13_oe_n,
	gpio_h13_in,
	gpio_h14_out,
	gpio_h14_oe_n,
	gpio_h14_in,
	gpio_h15_out,
	gpio_h15_oe_n,
	gpio_h15_in );

	output	[31:0]	h2h_haddr;
	output	[1:0]	h2h_htrans;
	output	h2h_hwrite;
	output	[2:0]	h2h_hsize;
	output	[2:0]	h2h_hburst;
	output	[3:0]	h2h_hprot;
	output	[31:0]	h2h_hwdata;
	input	[31:0]	h2h_hrdata;
	input	h2h_hreadyout;
	input	[1:0]	h2h_hresp;
	input	h2h_mclk;
	input	h2h_rstn;
	input	ahbslave_dma_req;
	input	ahbslave_dma_single;
	output	ahbslave_dma_ack;
	input	[3:0]	qspi_rxd;
	output	[3:0]	qspi_txd;
	output	qspi_sclk;
	output	qspi_ss;
	output	[3:0]	qspi_oen;
	input	ppm_clk;
	input	i2s_mst_clk;
	input	ppm_rstn;
	output	gpio_h0_out;
	output	gpio_h0_oe_n;
	input	gpio_h0_in;
	output	gpio_h1_out;
	output	gpio_h1_oe_n;
	input	gpio_h1_in;
	output	gpio_h2_out;
	output	gpio_h2_oe_n;
	input	gpio_h2_in;
	output	gpio_h3_out;
	output	gpio_h3_oe_n;
	input	gpio_h3_in;
	output	gpio_h4_out;
	output	gpio_h4_oe_n;
	input	gpio_h4_in;
	output	gpio_h5_out;
	output	gpio_h5_oe_n;
	input	gpio_h5_in;
	output	gpio_h6_out;
	output	gpio_h6_oe_n;
	input	gpio_h6_in;
	output	gpio_h7_out;
	output	gpio_h7_oe_n;
	input	gpio_h7_in;
	output	gpio_h8_out;
	output	gpio_h8_oe_n;
	input	gpio_h8_in;
	output	gpio_h9_out;
	output	gpio_h9_oe_n;
	input	gpio_h9_in;
	output	gpio_h10_out;
	output	gpio_h10_oe_n;
	input	gpio_h10_in;
	output	gpio_h11_out;
	output	gpio_h11_oe_n;
	input	gpio_h11_in;
	output	gpio_h12_out;
	output	gpio_h12_oe_n;
	input	gpio_h12_in;
	output	gpio_h13_out;
	output	gpio_h13_oe_n;
	input	gpio_h13_in;
	output	gpio_h14_out;
	output	gpio_h14_oe_n;
	input	gpio_h14_in;
	output	gpio_h15_out;
	output	gpio_h15_oe_n;
	input	gpio_h15_in;
	output	sleep_out;
	output	[15:0]	usr_reg;
	EF2_PHY_MCU #(
		.GPIO_L0("ENABLE"),
		.GPIO_L1("ENABLE"),
		.GPIO_L5("ENABLE"))
	mcu_inst(
		.ppm_clk(ppm_clk),
		.i2s_mst_clk(i2s_mst_clk),
		.ppm_rstn(ppm_rstn),
		.h2h_haddr(h2h_haddr),
		.h2h_htrans(h2h_htrans),
		.h2h_hwrite(h2h_hwrite),
		.h2h_hsize(h2h_hsize),
		.h2h_hburst(h2h_hburst),
		.h2h_hprot(h2h_hprot),
		.h2h_hwdata(h2h_hwdata),
		.h2h_hrdata(h2h_hrdata),
		.h2h_hreadyout(h2h_hreadyout),
		.h2h_hresp(h2h_hresp),
		.h2h_mclk(h2h_mclk),
		.h2h_rstn(h2h_rstn),
		.ahbslave_dma_req(ahbslave_dma_req),
		.ahbslave_dma_single(ahbslave_dma_single),
		.ahbslave_dma_ack(ahbslave_dma_ack),
		.sleep_out(sleep_out),
		.usr_reg(usr_reg),
		.qspi_rxd(qspi_rxd),
		.qspi_txd(qspi_txd),
		.qspi_sclk(qspi_sclk),
		.qspi_ss(qspi_ss),
		.qspi_oen(qspi_oen),
		.gpio_h_out({gpio_h15_out,gpio_h14_out,gpio_h13_out,gpio_h12_out,gpio_h11_out,gpio_h10_out,gpio_h9_out,gpio_h8_out,gpio_h7_out,gpio_h6_out,gpio_h5_out,gpio_h4_out,gpio_h3_out,gpio_h2_out,gpio_h1_out,gpio_h0_out}),
		.gpio_h_oe_n({gpio_h15_oe_n,gpio_h14_oe_n,gpio_h13_oe_n,gpio_h12_oe_n,gpio_h11_oe_n,gpio_h10_oe_n,gpio_h9_oe_n,gpio_h8_oe_n,gpio_h7_oe_n,gpio_h6_oe_n,gpio_h5_oe_n,gpio_h4_oe_n,gpio_h3_oe_n,gpio_h2_oe_n,gpio_h1_oe_n,gpio_h0_oe_n}),
		.gpio_h_in({gpio_h15_in,gpio_h14_in,gpio_h13_in,gpio_h12_in,gpio_h11_in,gpio_h10_in,gpio_h9_in,gpio_h8_in,gpio_h7_in,gpio_h6_in,gpio_h5_in,gpio_h4_in,gpio_h3_in,gpio_h2_in,gpio_h1_in,gpio_h0_in}));
endmodule