/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Project/AI8051_north_bridge/al_ip/soc_dtcm.v
 ** Date	:	2024 11 27
 ** TD version	:	4.6.121343
\************************************************************/

`timescale 1ns / 1ps

module soc_dtcm ( dob,dib,ceb,clkb,web,addrb,webbyte );
	output 		[31:0] dob;
	input  		[31:0] dib;
	input  		ceb;
	input  		clkb;
	input  		web;
	input  		[12:0] addrb;
	input  		[3:0] webbyte;


		EF2_PHY_BRAM256K #(
		.MODE("SP"),
		.REGMODE_B("NOREG"),
		.WRITEMODE_B("NORMAL"),
		.INIT_FILE("NONE"))

		inst (
		.dia(32'b0),
		.dib(dib),
		.cea(1'b0),
		.ceb(ceb),
		.ocea(1'b0),
		.oceb(1'b0),
		.clka(1'b0),
		.clkb(clkb),
		.wea(1'b0),
		.web(web),
		.rsta(1'b0),
		.rstb(1'b0),
		.addra(13'b0),
		.addrb(addrb),
		.weabyte(4'b0),
		.webbyte(webbyte),
		.doa(),
		.dob(dob));

endmodule