/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/xiaoyu.hong/AI8051_north_bridge/al_ip/sys_pll.v
 ** Date	:	2024 11 25
 ** TD version	:	4.6.121343
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               25.000000Mhz
//	Clock multiplication factor: 8
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000000MHZ	| 0.0000  DEG  
//		C1        	| 200.000000MHZ	| 180.0000 DEG  
//		C2        	| 25.000000 MHZ	| 0.0000  DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module sys_pll(refclk,
		reset,
		dclk,
		dcs,
		dwe,
		di,
		daddr,
		extlock,
		do,
		clk0_out,
		clk1_out,
		clk2_out);

	input refclk;
	input reset;
	input dclk;
	input dcs;
	input dwe;
	input [7:0]	di;
	input [5:0]	daddr;
	output extlock;
	output [7:0]	do;
	output clk0_out;
	output clk1_out;
	output clk2_out;

	wire clk0_buf;

	EF2_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	EF2_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.DYNCFG("ENABLE"),
		.FIN("25.000000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("ENABLE"),
		.GEN_BASIC_CLOCK("ENABLE"),
		.GMC_GAIN(2),
		.ICP_CURRENT(9),
		.KVCO(2),
		.LPF_CAPACITOR(1),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(1),
		.FBCLK_DIV(8),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(5),
		.CLKC0_CPHASE(4),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(5),
		.CLKC1_CPHASE(1),
		.CLKC1_FPHASE(4),
		.CLKC2_ENABLE("ENABLE"),
		.CLKC2_DIV(40),
		.CLKC2_CPHASE(39),
		.CLKC2_FPHASE(0),
		.PU_INTP("DISABLE"),
		.INTPI(0),
		.HIGH_SPEED_EN("DISABLE"),
		.SSC_ENABLE("DISABLE"),
		.SSC_MODE("Down"),
		.SSC_AMP(0.0000),
		.SSC_FREQ_DIV(0),
		.SSC_RNGE(0),
		.FREQ_OFFSET(0.0000),
		.OFFSET_MODE("EXT"),
		.FREQ_OFFSET_INT(0),
		.CLKC0_DUTY(0.5000),
		.CLKC0_DUTY_INT(3),
		.CLKC0_DUTY50("ENABLE"),
		.CLKC1_DUTY(0.5000),
		.CLKC1_DUTY_INT(3),
		.CLKC1_DUTY50("ENABLE")	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(1'b0),
		.extlock(extlock),
		.load_reg(1'b0),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(dclk),
		.dcs(dcs),
		.dwe(dwe),
		.di(di),
		.daddr(daddr),
		.do(do),
		.fbclk(clk0_out),
		.clkc({open, open, open, open, clk2_out, clk1_out, clk0_buf}),
		.ssc_en(1'b0),
		.frac_offset_valid(1'b0),
		.dsm_refclk(1'b0),
		.dsm_rst(reset));

endmodule
